### ISSUE TITLE
Project with path ':barcode_scanner_library' could not be found in project ':zebra_scanner_plugin'

### ISSUE THREAD

**Issue by bobandrew** [sanketwarule/zebra_scanner_plugin#1]
hi,
I added your plugin into my project and get below error. Could you suggest, how to fix this?

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\flutter\.pub-cache\hosted\pub.dartlang.org\zebra_scanner_plugin-0.0.6\android\build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':zebra_scanner_plugin'.
> Project with path ':barcode_scanner_library' could not be found in project ':zebra_scanner_plugin'.

**Comment by sanketwarule** [comment]
Hi @bobandrew 

Thank you for raising a concern, I have added the guide section in readme file.
Just go through the point #2 and #3
Specifically the Second and Third steps seems to be the ones related to your issue.

And for reference check the example app in the example directory of the plugin

**Comment by sanketwarule** [comment]
Hi @bobandrew , Please let me know if above comment is helpful to you and has solved your issue.
