### ISSUE TITLE
 AAPT: error: resource android:color/system_neutral1_300 not found.

### ISSUE THREAD

**Issue by iPatel007** [sanketwarule/zebra_scanner_plugin#3]
When I tried to create apk file by using terminal `flutter build apk` getting below error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':zebra_scanner_plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:3:5-94: AAPT: error: resource android:color/system_neutral1_1000 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:4:5-94: AAPT: error: resource android:color/system_neutral1_900 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:5:5-93: AAPT: error: resource android:color/system_neutral1_0 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:6:5-94: AAPT: error: resource android:color/system_neutral1_800 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:7:5-94: AAPT: error: resource android:color/system_neutral1_700 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:8:5-94: AAPT: error: resource android:color/system_neutral1_600 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:9:5-94: AAPT: error: resource android:color/system_neutral1_500 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:10:5-94: AAPT: error: resource android:color/system_neutral1_400 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:11:5-94: AAPT: error: resource android:color/system_neutral1_300 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:12:5-94: AAPT: error: resource android:color/system_neutral1_200 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:13:5-94: AAPT: error: resource android:color/system_neutral1_100 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:14:5-93: AAPT: error: resource android:color/system_neutral1_50 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:15:5-93: AAPT: error: resource android:color/system_neutral1_10 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:16:5-102: AAPT: error: resource android:color/system_neutral2_1000 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:17:5-102: AAPT: error: resource android:color/system_neutral2_900 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:18:5-101: AAPT: error: resource android:color/system_neutral2_0 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:19:5-102: AAPT: error: resource android:color/system_neutral2_800 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:20:5-102: AAPT: error: resource android:color/system_neutral2_700 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:21:5-102: AAPT: error: resource android:color/system_neutral2_600 not found.

     ERROR:/Users/ipatel/.gradle/caches/transforms-3/6607a3f1c65f0bf7ff8af3a51d0c0b5f/transformed/material-1.6.1/res/values-v31/values-v31.xml:22:5-102: AAPT: error: resource android:color/system_neutral2_500 not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m
Running Gradle task 'assembleRelease'...                           61.3s
Gradle task assembleRelease failed with exit code 1

**Comment by singh-sukhdip** [comment]
I am also facing the same issue. Did you solve it?

**Comment by haitham-alabdullah** [comment]
Declare your manifest header like this:
```java
<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
    xmlns:tools="http://schemas.android.com/tools">
```

add this line under applicationtag:
```java
tools:replace="android:name, label"
```

**Comment by sanketwarule** [comment]
Hello  everyone,

I want to let you know that I currently do not have access to a Zebra scanner device. However, I've developed a Zebra scanner integration and made it available publicly here.

I encourage you to explore the project, contribute, and help enhance its functionality. Your contributions will not only help improve the project but also benefit other developers in the community.

Thank you for your support and collaboration!

Best regards,
Sanket Warule
